[build]
  base = "frontend/"
  publish = "dist/mempool/browser/en-US/"
  command = "npm run config:defaults:mempool && npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://mempool.space/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/ws"
  to = "wss://mempool.space/api/v1/ws"
  status = 101
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 