[build]
  base = "frontend/"
  publish = "frontend/dist/"
  command = "npm run config:defaults:mempool && npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://mempool.space/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 